# Basic
title: Tiger Zhang
subtitle: Welcome to Tiger's zone
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: This is a blog site hosted on Github Pages.
creator: <a href="https://github.com/TigerAVAF6R">@TigerAVAF6R</a>

url: "https://github.com/TigerAVAF6R"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/TigerAVAF6R'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: onevcat
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: 13889529219@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
